COMP: Update VersionNumber.cxx to fix build against C++11 prior CWG 1270
This commit fixes error like the following introduced in 93bb4716 and
reported when building SMTK on system providing C++11 prior to the CWG
1270 revision:

  /path/to/smtk/smtk/common/VersionNumber.cxx:22:34: error: array must be initialized with a brace-enclosed initializer
     : std::array<int, 3>{ -1, 0, 0 }
                                    ^

See https://en.cppreference.com/w/cpp/container/array#Example

Fixes #455